apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotcom-deployment
  namespace: dotcom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotcom
  template:
    metadata:
      labels:
        app: dotcom
    spec:
      containers:
      - name: dotcom
        image: julianone/dotcom:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: HOST
          value: "julian-one.com"
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: dotcom-config
              key: PORT
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: dotcom-secret
              key: SECRET
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: dotcom-secret
              key: DB_USER
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: dotcom-secret
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: dotcom-secret
              key: DB_NAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dotcom-secret
              key: DB_PASSWORD
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: dotcom-secret
              key: DB_PORT
